# Generated by Django 6.0.7 on 2026-08-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_band'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('records', 'Records'), ('clothing', 'Clothing'), ('posters', 'Posters'), ('miscellaneous', 'Misc')], max_length=20),
        ),
    ]
